--require("luasnip.loaders.from_vscode").load({ paths = { "./snippets" } })
--
--require('snippy').setup({
    --mappings = {
        --is = {
            --['<Tab>'] = 'expand_or_advance',
            --['<S-Tab>'] = 'previous',
        --},
        --nx = {
            --['<leader>x'] = 'cut_text',
        --},
    --},
--})
